# @file
# .travis.yml - PKP Plugins Integration

language: php
dist: trusty

addons:
  firefox: "45.9.0esr"
  apt:
    update: true

sudo: required

php:
  - 7.2
env:
  - APPLICATION=ojs BRANCH=master TEST=mysql
  - APPLICATION=ojs BRANCH=master TEST=pgsql

install:
  # Prepare OJS/OMP environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install && npm run build
  # Prepare server environment
  - source lib/pkp/tools/travis/start-xvfb.sh
  - lib/pkp/tools/travis/start-selenium.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/importexport/quickSubmit
  # Install OJS/OMP & prep data environment
  - lib/pkp/lib/vendor/phpunit/phpunit/phpunit --configuration lib/pkp/tests/phpunit-env1.xml tests/data/10-InstallationTest.php
  - lib/pkp/lib/vendor/phpunit/phpunit/phpunit --configuration lib/pkp/tests/phpunit-env1.xml tests/data/20-CreateContextTest.php
  - lib/pkp/tools/travis/dump-database.sh
script:
  - lib/pkp/lib/vendor/phpunit/phpunit/phpunit --debug -v --configuration lib/pkp/tests/phpunit-env2.xml plugins/importexport/quickSubmit/tests/functional/QuickSubmitFunctionalTest.php
